name: v8 Main - Pre-release

on:
  push:
    tags:
    - "v8.[0-9]+.[0-9]+-[a-z]*[0-9]+"
  workflow_dispatch: #Manual

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set VERSION variable from tag 1
      run: echo "VERSION1=${$env:GITHUB_REF/refs\/tags\/v/}" >> $env:GITHUB_ENV

    - name: Set VERSION variable from tag 2
      run: |
        git fetch --tags
        echo "VERSION2=$(git describe --tags --abbrev=0)" >> $env:GITHUB_ENV

    - name: Test 1
      run: echo "The version1 tag is $env:VERSION1"
      
    - name: Test 2
      run: echo "The version2 tag is $env:VERSION2"
