name: v8 Main - Pre-release

on:
  push:
    tags:
    - "v8.[0-9]+.[0-9]+-[a-z]*[0-9]+"

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    
    - name: Restore Packages
      run: nuget restore src/Method4.UmbracoMigrator.Source.sln
    
    - name: Pack Core Project
      run: dotnet pack src/Method4.UmbracoMigrator.Source.Core/Method4.UmbracoMigrator.Source.Core.csproj --configuration Release /p:Version=${VERSION} --output .
      
    - name: Pack Main Project
      run: dotnet pack src/Method4.UmbracoMigrator.Source/Method4.UmbracoMigrator.Source.csproj --configuration Release /p:Version=${VERSION} --output .
      
    - name: Push Core Project
      run: dotnet nuget push Method4.UmbracoMigrator.Source.Core.${VERSION}.nupkg --api-key ${NUGET_API_KEY} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    - name: Push Main Project
      run: dotnet nuget push Method4.UmbracoMigrator.Source.${VERSION}.nupkg --api-key ${NUGET_API_KEY} --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
