name: v8 Main - Release

on:
  push:
    tags:
    - "v8.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4

    - name: Set VERSION variable from tag
      run: |
        git fetch --tags
        $tag = git describe --tags --abbrev=0
        if ($tag.StartsWith("v")) {
          $cleanTag = $tag.Substring(1)
        } else {
          $cleanTag = $tag
        }
        echo "VERSION=$cleanTag" >> $env:GITHUB_ENV

    - name: Show VERSION
      run: echo "VERSION is $env:VERSION"
    
    - name: Pack Core Project
      run: dotnet pack src/Method4.UmbracoMigrator.Source.Core/Method4.UmbracoMigrator.Source.Core.csproj -p:PackageVersion=$env:VERSION --configuration Release --output .
      
    - name: Pack Main Project
      run: dotnet pack src/Method4.UmbracoMigrator.Source/Method4.UmbracoMigrator.Source.csproj -p:PackageVersion=$env:VERSION --configuration Release --output .
      
    - name: Push Core Project
      run: dotnet nuget push Method4.UmbracoMigrator.Source.Core.$env:VERSION.nupkg --api-key $env:NUGET_API_KEY --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    - name: Push Main Project
      run: dotnet nuget push Method4.UmbracoMigrator.Source.$env:VERSION.nupkg --api-key $env:NUGET_API_KEY --source https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
